language: python
dist: xenial
matrix:
  include:
    - name: 'Plone'
      python: 3.7
      env: TEST_SUITE=plone ZSERVER_PORT=55001
    - name: 'Guillotina Tests'
      python: 3.7
      env: TEST_SUITE=guillotina
cache:
  pip: true
  yarn: true
  directories:
    - $HOME/buildout-cache
    - ~/.cache
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - xvfb
      - libgtk2.0-0
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libxss1
      - libasound2
before_install:
  - nvm install 12;
  - if [ "$TEST_SUITE" == "plone" ]; then
    mkdir -p $HOME/buildout-cache/{eggs,downloads};
    mkdir $HOME/.buildout;
    echo "[buildout]" > $HOME/.buildout/default.cfg;
    echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg;
    echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg;
    fi
install:
  - if [ "$TEST_SUITE" == "plone" ]; then
    make build-backend;
    fi
  - npm -g install yo
  - npm -g install ./
  - yo create-volto-app my-volto-app --description "test volto project" --skip-addons --skip-install
  - yarn install --frozen-lockfile
  - yarn add cypress cypress-file-upload@3.5.3 start-server-and-test xmlrpc
  - yarn cy:install
script:
  - if [ "$TEST_SUITE" == "guillotina" ]; then
    yarn ci:cypress:run:guillotina;
    fi
  - if [ "$TEST_SUITE" == "plone" ]; then
    yarn ci:cypress:run;
    fi
after_success:
  - npm pack --dry-run
