language: python
dist: xenial
matrix:
  include:
    - name: 'Plone'
      python: 3.7
      env: TEST_SUITE=plone ZSERVER_PORT=55001
    - name: 'Guillotina Tests'
      python: 3.7
      env: TEST_SUITE=guillotina
    - name: 'Unit Tests'
      env: TEST_SUITE=unit
cache:
  pip: true
  directories:
    - node_modules
    - $HOME/buildout-cache
sudo: required
services:
  - docker
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - nvm install 10.14.2;
  - if [ "$TEST_SUITE" != "unit" ]; then
    mkdir webdriver;
    wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz;
    tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C webdriver;
    wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip;
    unzip chromedriver_linux64.zip -d webdriver;
    export PATH=$PATH:$(pwd)/webdriver;
    fi
  - if [ "$TEST_SUITE" == "plone" ]; then
    mkdir -p $HOME/buildout-cache/{eggs,downloads};
    mkdir $HOME/.buildout;
    echo "[buildout]" > $HOME/.buildout/default.cfg;
    echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg;
    echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg;
    fi

install:
  - if [ "$TEST_SUITE" == "plone" ]; then
    make build-backend;
    fi
  - pip install -r requirements-tests.txt;
  - yarn
before_script:
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
script:
  - if [ "$TEST_SUITE" == "guillotina" ]; then
    PYTHONPATH=$(pwd)/tests travis_retry pybot -v BROWSER:headlesschrome -v API:Guillotina tests;
    fi
  - if [ "$TEST_SUITE" == "plone" ]; then
    PYTHONPATH=$(pwd)/tests ZSERVER_PORT=55001 travis_retry api/bin/pybot -v BROWSER:headlesschrome -v API:Plone tests;
    fi
