version: '3'
services:
  postgres:
    image: postgres:10
    container_name: postgres_test
    environment:
        POSTGRES_DB: guillotina
        POSTGRES_USER: guillotina
  guillotina:
    image: plone/guillotina_cms:volto
    command: sh -c "sleep 5 && g -c /usr/src/app/config.yml"
    ports:
    - "8081:8081"
    - "50101:50101"
    links:
     - postgres
    volumes:
      - ${PWD}/g-api/config.yml:/usr/src/app/config.yml
