version: '3'
services:
  postgres:
    image: postgres:10
    container_name: postgres_test
    environment:
        POSTGRES_DB: guillotina
        POSTGRES_USER: guillotina
  guillotina:
    image: plone/guillotina_cms@sha256:5b204781f101506ab26f70b84a761f80a32393e8a2ccfc93851083bfa155d0b4
    command: sh -c "sleep 5 && g -c /usr/src/app/config.yml"
    ports:
    - "8081:8081"
    - "50101:50101"
    links:
     - postgres
    volumes:
      - ${PWD}/g-api/config.yml:/usr/src/app/config.yml
